name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: |        
        echo "Running tests..." 
        npx cucumber-js --config cucumber.js --parallel 3 --format progress --format summary 


      - name: Install Allure Commandline
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          if [ -d "allure-results" ]; then
            allure generate allure-results -o allure-report --clean
          fi

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report